
package com.oracle.wsclient;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookmarkWebService", targetNamespace = "http://gf2wls.samples.oracle.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookmarkWebService {


    /**
     * 
     * @return
     *     returns java.util.List<com.oracle.wsclient.Bookmark>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://gf2wls.samples.oracle.com/", className = "com.oracle.wsclient.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://gf2wls.samples.oracle.com/", className = "com.oracle.wsclient.FindAllResponse")
    @Action(input = "http://gf2wls.samples.oracle.com/BookmarkWebService/findAllRequest", output = "http://gf2wls.samples.oracle.com/BookmarkWebService/findAllResponse")
    public List<Bookmark> findAll();

    /**
     * 
     * @param id
     * @param entity
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "edit", targetNamespace = "http://gf2wls.samples.oracle.com/", className = "com.oracle.wsclient.Edit")
    @Action(input = "http://gf2wls.samples.oracle.com/BookmarkWebService/edit")
    public void edit(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "entity", targetNamespace = "")
        Bookmark entity);

    /**
     * 
     * @param id
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "remove", targetNamespace = "http://gf2wls.samples.oracle.com/", className = "com.oracle.wsclient.Remove")
    @Action(input = "http://gf2wls.samples.oracle.com/BookmarkWebService/remove")
    public void remove(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://gf2wls.samples.oracle.com/", className = "com.oracle.wsclient.Count")
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://gf2wls.samples.oracle.com/", className = "com.oracle.wsclient.CountResponse")
    @Action(input = "http://gf2wls.samples.oracle.com/BookmarkWebService/countRequest", output = "http://gf2wls.samples.oracle.com/BookmarkWebService/countResponse")
    public int count();

    /**
     * 
     * @param id
     * @return
     *     returns com.oracle.wsclient.Bookmark
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "find", targetNamespace = "http://gf2wls.samples.oracle.com/", className = "com.oracle.wsclient.Find")
    @ResponseWrapper(localName = "findResponse", targetNamespace = "http://gf2wls.samples.oracle.com/", className = "com.oracle.wsclient.FindResponse")
    @Action(input = "http://gf2wls.samples.oracle.com/BookmarkWebService/findRequest", output = "http://gf2wls.samples.oracle.com/BookmarkWebService/findResponse")
    public Bookmark find(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param entity
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "create", targetNamespace = "http://gf2wls.samples.oracle.com/", className = "com.oracle.wsclient.Create")
    @Action(input = "http://gf2wls.samples.oracle.com/BookmarkWebService/create")
    public void create(
        @WebParam(name = "entity", targetNamespace = "")
        Bookmark entity);

}
