
package com.oracle.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookmarkWebService", targetNamespace = "http://gf2wls.samples.oracle.com/", wsdlLocation = "http://localhost:7001/bookmark-javaee6/BookmarkWebService?WSDL")
public class BookmarkWebService_Service
    extends Service
{

    private final static URL BOOKMARKWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKMARKWEBSERVICE_EXCEPTION;
    private final static QName BOOKMARKWEBSERVICE_QNAME = new QName("http://gf2wls.samples.oracle.com/", "BookmarkWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7001/bookmark-javaee6/BookmarkWebService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKMARKWEBSERVICE_WSDL_LOCATION = url;
        BOOKMARKWEBSERVICE_EXCEPTION = e;
    }

    public BookmarkWebService_Service() {
        super(__getWsdlLocation(), BOOKMARKWEBSERVICE_QNAME);
    }

    public BookmarkWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKMARKWEBSERVICE_QNAME, features);
    }

    public BookmarkWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, BOOKMARKWEBSERVICE_QNAME);
    }

    public BookmarkWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKMARKWEBSERVICE_QNAME, features);
    }

    public BookmarkWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookmarkWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookmarkWebService
     */
    @WebEndpoint(name = "BookmarkWebServicePort")
    public BookmarkWebService getBookmarkWebServicePort() {
        return super.getPort(new QName("http://gf2wls.samples.oracle.com/", "BookmarkWebServicePort"), BookmarkWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookmarkWebService
     */
    @WebEndpoint(name = "BookmarkWebServicePort")
    public BookmarkWebService getBookmarkWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gf2wls.samples.oracle.com/", "BookmarkWebServicePort"), BookmarkWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKMARKWEBSERVICE_EXCEPTION!= null) {
            throw BOOKMARKWEBSERVICE_EXCEPTION;
        }
        return BOOKMARKWEBSERVICE_WSDL_LOCATION;
    }

}
